import { tokenize } from './tokenizer.ts';
import { parse, type Statement } from './parser.ts';
import { generate } from './generator.ts';


const sources: [string, string][] = [
    ['musicology', 'Musicology'],
    ['pomo', 'Postmodern'],
    ['marriage', 'Good Marriage'],
    ['securities', 'Finance Company Names'],
    ['crackpot', 'Crackpot'],
    ['manifesto', 'Manifesto'],
    ['legal', 'Random Legalese'],
    ['mykeExcuses', 'Myke’s Receipts'],
    ['sample', 'Testing File'],
];

const titles: {[key: string]: string} = {
    'musicology': 'Automatic Postmodern/New Musicology Essay Generator (Cuthbert)',
    'pomo': 'The Classic Postmodernism Generator by Andrew C. Bulhak',
    'marriage': 'Random Lists of Tips for a Good Relationship/Marriage (Cuthbert)',
    'securities': 'Automatically Generated Securities Firms',
    'crackpot': 'Crackpot Rants (by Andrew C. Bulhak)',
    'manifesto': 'Manifesto Generator (by Andrew C. Bulhak)',
    'legal': 'Random Legalese (by "Mitch")',
    'mykeExcuses': 'Randomly generated reasons for Myke Cuthbert\'s receipts',
    'sample': 'A test of all the capabilities of the TypeScript Dada Generator',
};

const descriptions: {[key: string]: string} = {
    'musicology': `An automated system by Michael Scott Asato Cuthbert (based on work
        by Andrew C. Bulhak) to automatically generate new musicology style essays.
        A parody of the current state of prose.`,
    'pomo': 'The Classic Postmodernism Generator by Andrew C. Bulhak',
    'marriage': 'Random Lists of Tips for a Good Relationship/Marriage generated by '
        + 'Michael Scott Asato Cuthbert, partially for fun (resembling Cosmopolitan, Elle, '
        + 'Redbook, etc.) and partially because it is good to remember what actually works.',
    'securities': 'Automatically Generated Securities Firm names -- made for '
        + 'a publication by Lisa D. Friedland about detecting Security fraud, but '
        + 'where no names of actual firms could be used. '
    ,
    'crackpot': 'Crackpot Rants (by Andrew C. Bulhak)',
    'manifesto': 'Manifesto Generator (by Andrew C. Bulhak)',
    'legal': 'Random Legalese (by "Mitch")',
    'mykeExcuses': 'Randomly generated reasons for Myke Cuthbert\'s receipts',
    'sample': 'A test of all the capabilities of the TypeScript Dada Generator',
};


const select = document.createElement('select');
select.id = 'source-select';
// Populate the dropdown
for (const [file, label] of sources) {
  const option = document.createElement('option');
  option.value = file;
  option.textContent = label;
  select.appendChild(option);
}
document.body.appendChild(select);

const file_to_url = (filename: string): string => `scripts/${filename}.pb`;

select.addEventListener('change', () => {
  const file = select.value;
  history.replaceState(null, '', `?file=${encodeURIComponent(file)}`);
  loadAndRender(file).catch(console.error);
});

const params = new URLSearchParams(location.search);
const file = params.get('file') ?? 'musicology';
select.value = file;

async function loadAndRender(file: string) {
    const fileUrl = file_to_url(file);
    try {
        const res = await fetch(fileUrl);
        const text = await res.text();
        if (text.trim().startsWith('<')) {
            // noinspection ExceptionCaughtLocallyJS
            throw new Error(`Expected .pb file, got HTML instead (from ${fileUrl})`);
        }
        const tokens = tokenize(text);
        const statements: Statement[] = parse(tokens);
        const first = statements.find(s => s.type === 'rule' && !s.resource);
        const entry = first && first.type === 'rule' ? first.name : 'main';
        const html = generate(statements, entry, 'html');
        document.body.innerHTML = html;
        document.body.appendChild(select);
    } catch (err) {
        document.body.innerHTML = `<pre>Error: ${(err as Error).message}</pre>`;
        document.body.appendChild(select);
    }
    document.title = titles[file] || 'Automatic Typescript Dada Generator based on PB';

    const meta = document.createElement('meta');
    meta.setAttribute('name', 'description');
    meta.setAttribute(
        'content',
        descriptions[file] || 'An essay generated by the Automatic TypeScript Dada Generator'
    );
    document.head.append(meta);
    document.body.classList.remove('hide-while-loading');
}

loadAndRender(file).catch(console.error);
